### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by lisandroseia** [memelopez/toDoList-webpack-mv#4]
Hello Elmer
you did an excellent job, I will let this issue so we can comment on all the things we think you could improve!

**Comment by hendridg** [comment]
# Great job @memelopez 

- Clean code
- No linter problem

![](https://media2.giphy.com/media/l3fQc3aCV0HqpzWcU/giphy.gif)



Cheers and Happy coding!👏👏👏

**Comment by andres-condezo** [comment]
## HI @memelopez!
Good job so far!

## Highlights:
- You have a clean and orderly code. 🟢 

![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 

### Suggestion:
- You can add these lines to your Webpack configuration to see the changes you make in your index.html in real-time without having to reload your browser:
- ` devServer: {
    hot:true,
    open:true,
    watchFiles: ['src/**/*']
  },`

Cheers and Happy coding!
